sonar.projectKey=junit4
sonar.projectName=JUnit 4
sonar.projectVersion=4.13.2
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.host.url=http://localhost:9000
sonar.login=admin
sonar.password=admin123
